### ISSUE TITLE
Support "choices" names with more than one char

### ISSUE THREAD

**Issue by Nhqml** [prologin/iorgen#29]
When using "choices" option, iorgen is not able to validate the test files if the choices values contains more than one char.

e.g: You will get `Input is invalid: Line X: x not in {b, g, r}` when your choices are *red*, *green*, *blue*

**Comment by Shaac** [comment]
This one is a bit tricky.

“choices” are currently available only for int and char. So this is currently expected that it would not work for strings.

However, “choices” is meant to work for list of int, or list of list of int. The same for list of char. Since a string is kind of a list of char, this is interpreted like: “every char in thing string must be one on the following”.

So there is a bug here: _red_, _green_ and _blue_ should trigger a warning, because iorgen is only expecting the first letter (that is what happen).

But as if we were to add support for string, this is where it becomes tricky: how to clearly keep the two behaviors? We still want to be able to have list of characters with a “choice” for the characters. Maybe the difference between a list of char and a string has to be made here, but I’m afraid it could lead to confusions.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/iorgen/-/issues/29
